sudo: false
language: java
jdk:
  - oraclejdk8
env:
  - CC=clang CXX=clang++
install:
  - mvn -f root/pom.xml install
script: mvn -B -q -fae test -Ptest-exclude-native,-build-user-guide -DlogQuiet
branches:
  only:
    - master
